default: &default
  adapter: postgresql
  encoding: unicode
  port: 5432
  host: localhost
  username: postgres
  password: Hirumi01
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: Budget_app_development

test:
  <<: *default
  database: Budget_app_test

production:
  <<: *default
  database: Budget_app_production
  username: Budget_app
  password: <%= ENV["BUDGET_APP_DATABASE_PASSWORD"] %>
